export const SHOW_INPUT_FOR_TITLE = 'SHOW_INPUT_FOR_TITLE';
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST';
export const CHANGE_ITEM = 'CHANGE_ITEM';
export const HANDLE_EDIT_LIST = 'HANDLE_EDIT_LIST';
export const SHOW_INPUT_FOR_EDIT = 'SHOW_INPUT_FOR_EDIT';
export const CHANGE_LIST_TITLE = 'CHANGE_LIST_TITLE';
