export const SHOW_INPUT_FOR_TITLE = 'SHOW_INPUT_FOR_TITLE';
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST';
export const CHANGE_ITEM = 'CHANGE_ITEM';

